version: '3.4'

volumes:
  redis: {}
  postgres: {}

services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
    ports:
      - 127.0.0.1:6379:6379

  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  api:
    restart: always
    build: .
    environment:
      APP_DB_URL: postgresql://postgres:postgres@postgres/postgres
      APP_REDIS_QUEUE_URL: redis://redis:6379/1