version: '3.4'

volumes:
  node_modules: {}

services:
  redis:
    ports:
      - 127.0.0.1:6379:6379

  mongo:
    ports:
      - 127.0.0.1:27017:27017

  api:
    build:
      target: dev
    command: yarn dev:watch
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
