version: '3.4'

services:
  task:
    build:
      context: .
      target: dev
    depends_on:
      - mongo
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      APP_MONGO_URL: mongodb://mongo/db
    ports:
      - 5001:9229