version: '3.4'

volumes:
  mongo: {}
  redis: {}
  postgres: {}

services:
  redis:
    image: redis:alpine
    volumes:
      - redis:/data

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db

  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer:alpine
    restart: always
    ports:
      - 5012:8080

  api:
    build: .
    depends_on:
      - mongo
    environment:
      APP_MONGO_URL: mongodb://mongo/db
      APP_REDIS_QUEUE_URL: redis://redis:6379/1