version: '3.4'

volumes:
  redis: {}
  postgres: {}

services:
  redis:
    image: redis:alpine
    volumes:
      - redis:/data

  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer:alpine
    restart: always
    ports:
      - 5012:8080

  api:
    build: .
    environment:
      APP_DB_URL: postgresql://postgres:postgres@postgres/postgres
      APP_REDIS_QUEUE_URL: redis://redis:6379/1