version: '3.4'

volumes:
  node_modules: {}

services:
  redis:
    ports:
      - 127.0.0.1:6379:6379

  postgres:
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 5012:8080

  api:
    build:
      target: dev
    command: yarn dev
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
